package desktop

import (
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
)

// Installer handles fnOS application packaging and appcenter-cli interaction.
type Installer struct {
	mu               sync.Mutex
	cliPath          string
	appsDir          string
	rootIconPath     string
	hasAppcenterCLI  bool
}

// NewInstaller creates a new fnOS package installer.
func NewInstaller(dataDir string, rootIconPath string) *Installer {
	appsDir := filepath.Join(dataDir, "apps")
	_ = os.MkdirAll(appsDir, 0755)

	cliPath, found := findAppcenterCLI()

	inst := &Installer{
		cliPath:         cliPath,
		appsDir:         appsDir,
		rootIconPath:    rootIconPath,
		hasAppcenterCLI: found,
	}

	if found {
		slog.Info("Found fnOS appcenter-cli", "path", cliPath)
	} else {
		slog.Info("fnOS appcenter-cli not found (running in standalone/simulation mode)")
	}

	return inst
}

// HasCLI returns whether appcenter-cli is detected on the host.
func (i *Installer) HasCLI() bool {
	return i.hasAppcenterCLI
}

func findAppcenterCLI() (string, bool) {
	paths := []string{
		"/var/apps/appcenter/target/bin/appcenter-cli",
		"/usr/bin/appcenter-cli",
		"/usr/local/bin/appcenter-cli",
		"/host/root/usr/bin/appcenter-cli",
		"/host/root/var/apps/appcenter/target/bin/appcenter-cli",
	}

	for _, p := range paths {
		if fi, err := os.Stat(p); err == nil && !fi.IsDir() {
			return p, true
		}
	}

	if p, err := exec.LookPath("appcenter-cli"); err == nil {
		return p, true
	}

	return "", false
}

// AppcenterPackageConfig holds fields to generate an fnOS package.
type AppcenterPackageConfig struct {
	AppName     string
	Title       string
	Desc        string
	Port        int
	Protocol    string
	Path        string
	UIType      string // "url" or "iframe"
	AllUsers    bool
	IconPath    string
}

// BuildPackage creates the fnOS app structure on disk.
func (i *Installer) BuildPackage(cfg AppcenterPackageConfig) (string, error) {
	pkgDir := filepath.Join(i.appsDir, cfg.AppName)
	_ = os.RemoveAll(pkgDir)

	dirs := []string{
		pkgDir,
		filepath.Join(pkgDir, "app", "ui", "images"),
		filepath.Join(pkgDir, "cmd"),
		filepath.Join(pkgDir, "config"),
	}
	for _, d := range dirs {
		if err := os.MkdirAll(d, 0755); err != nil {
			return "", fmt.Errorf("创建目录失败 %s: %w", d, err)
		}
	}

	// 1. Manifest
	manifestContent := fmt.Sprintf(`appname=%s
version=1.0.0
display_name=%s
desc=%s
arch=x86_64
platform=all
source=thirdparty
maintainer=put-port-on-desktop
distributor=put-port-on-desktop
os_min_version=0.9.0
install_type=root
desktop_uidir=ui
desktop_applaunchname=%s
checkport=false
`, cfg.AppName, cfg.Title, cfg.Desc, cfg.AppName)

	if cfg.Port > 0 {
		manifestContent += fmt.Sprintf("service_port=%d\n", cfg.Port)
	}

	if err := os.WriteFile(filepath.Join(pkgDir, "manifest"), []byte(manifestContent), 0644); err != nil {
		return "", err
	}

	// 2. UI Config
	portStr := ""
	if cfg.Port > 0 {
		portStr = strconv.Itoa(cfg.Port)
	}
	proto := cfg.Protocol
	if proto == "" {
		proto = "http"
	}
	urlPath := cfg.Path
	if urlPath == "" {
		urlPath = "/"
	}
	uiType := cfg.UIType
	if uiType == "" {
		uiType = "url"
	}

	uiConfigMap := map[string]interface{}{
		".url": map[string]interface{}{
			cfg.AppName: map[string]interface{}{
				"title":     cfg.Title,
				"icon":      "images/icon_{0}.png",
				"type":      uiType,
				"protocol":  proto,
				"port":      portStr,
				"url":       urlPath,
				"allUsers":  cfg.AllUsers,
				"noDisplay": false,
			},
		},
	}
	uiJson, err := json.MarshalIndent(uiConfigMap, "", "    ")
	if err != nil {
		return "", err
	}
	if err := os.WriteFile(filepath.Join(pkgDir, "app", "ui", "config"), uiJson, 0644); err != nil {
		return "", err
	}

	// 3. Icon
	destIcon := filepath.Join(pkgDir, "app", "ui", "images", "icon_{0}.png")
	i.copyIcon(cfg.IconPath, destIcon)

	// 4. Lifecycle scripts
	mainScript := `#!/bin/bash
case $1 in
start|stop)
    exit 0
    ;;
status)
    exit 0
    ;;
*)
    exit 1
    ;;
esac
`
	if err := os.WriteFile(filepath.Join(pkgDir, "cmd", "main"), []byte(mainScript), 0755); err != nil {
		return "", err
	}

	emptyScript := "#!/bin/bash\nexit 0\n"
	for _, s := range []string{"install_init", "install_callback", "uninstall_init", "uninstall_callback"} {
		if err := os.WriteFile(filepath.Join(pkgDir, "cmd", s), []byte(emptyScript), 0755); err != nil {
			return "", err
		}
	}

	// 5. Config files
	privilegeJson := `{"defaults":{"run-as":"root"}}`
	_ = os.WriteFile(filepath.Join(pkgDir, "config", "privilege"), []byte(privilegeJson), 0644)
	_ = os.WriteFile(filepath.Join(pkgDir, "config", "resource"), []byte("{}"), 0644)

	// 6. License
	licenseText := fmt.Sprintf("MIT License\n\nGenerated by PutPortOnDesktop for %s\n", cfg.Title)
	_ = os.WriteFile(filepath.Join(pkgDir, "LICENSE"), []byte(licenseText), 0644)

	return pkgDir, nil
}

func (i *Installer) copyIcon(srcPath, destPath string) {
	if srcPath != "" {
		if data, err := os.ReadFile(srcPath); err == nil && len(data) > 0 {
			_ = os.WriteFile(destPath, data, 0644)
			return
		}
	}
	// Fallback to product icon
	if i.rootIconPath != "" {
		if data, err := os.ReadFile(i.rootIconPath); err == nil && len(data) > 0 {
			_ = os.WriteFile(destPath, data, 0644)
			return
		}
	}
}

// InstallItem registers a DesktopItem into fnOS.
func (i *Installer) InstallItem(item DesktopItem) error {
	i.mu.Lock()
	defer i.mu.Unlock()

	appName := "put-port." + sanitizeAppName(item.ID)
	port := item.Port
	path := item.Path
	if item.Mode == ModeShortcut {
		// Pure shortcut
		port = 0
		path = item.TargetURL
	}

	pkgDir, err := i.BuildPackage(AppcenterPackageConfig{
		AppName:  appName,
		Title:    item.Name,
		Desc:     item.Desc,
		Port:     port,
		Protocol: item.Protocol,
		Path:     path,
		UIType:   item.UIType,
		AllUsers: item.AllUsers,
		IconPath: item.Icon,
	})
	if err != nil {
		return fmt.Errorf("构建应用包失败: %w", err)
	}

	if !i.hasAppcenterCLI {
		slog.Info("应用包已构建 (模拟模式)", "appName", appName, "pkgDir", pkgDir)
		return nil
	}

	// Uninstall first if exists to ensure clean reinstall
	_ = exec.Command(i.cliPath, "uninstall", appName).Run()

	cmd := exec.Command(i.cliPath, "install-local", "--volume", "1")
	cmd.Dir = pkgDir
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("appcenter-cli install-local 失败: %w (详情: %s)", err, strings.TrimSpace(string(output)))
	}

	_ = exec.Command(i.cliPath, "start", appName).Run()
	slog.Info("成功注册桌面应用", "appName", appName)
	return nil
}

// UninstallItem unregisters a DesktopItem from fnOS.
func (i *Installer) UninstallItem(itemID string) error {
	i.mu.Lock()
	defer i.mu.Unlock()

	appName := "put-port." + sanitizeAppName(itemID)
	pkgDir := filepath.Join(i.appsDir, appName)
	_ = os.RemoveAll(pkgDir)

	if !i.hasAppcenterCLI {
		slog.Info("应用包已删除 (模拟模式)", "appName", appName)
		return nil
	}

	_ = exec.Command(i.cliPath, "stop", appName).Run()
	output, err := exec.Command(i.cliPath, "uninstall", appName).CombinedOutput()
	if err != nil {
		slog.Warn("卸载应用失败", "appName", appName, "output", strings.TrimSpace(string(output)))
	}
	return nil
}

// SyncSelfApp ensures put-port-on-desktop itself is registered on fnOS desktop with user settings.
func (i *Installer) SyncSelfApp(settings Settings) error {
	i.mu.Lock()
	defer i.mu.Unlock()

	appName := "put-port-on-desktop"
	pkgDir, err := i.BuildPackage(AppcenterPackageConfig{
		AppName:  appName,
		Title:    settings.PortalName,
		Desc:     "监控本机端口占用，并将服务与端口放置在飞牛OS桌面",
		Port:     settings.PortalPort,
		Protocol: "http",
		Path:     "/",
		UIType:   settings.PortalUIType,
		AllUsers: settings.PortalAllUsers,
		IconPath: i.rootIconPath,
	})
	if err != nil {
		return fmt.Errorf("构建自身应用包失败: %w", err)
	}

	if !i.hasAppcenterCLI {
		slog.Info("产品自身桌面包已准备就绪 (模拟模式)", "appName", appName, "pkgDir", pkgDir)
		return nil
	}

	// Check if already installed
	cmdList := exec.Command(i.cliPath, "list")
	output, err := cmdList.CombinedOutput()
	isInstalled := err == nil && strings.Contains(string(output), appName)

	if isInstalled {
		// Update configuration
		_ = exec.Command(i.cliPath, "stop", appName).Run()
		_ = exec.Command(i.cliPath, "uninstall", appName).Run()
	}

	installCmd := exec.Command(i.cliPath, "install-local", "--volume", "1")
	installCmd.Dir = pkgDir
	if out, err := installCmd.CombinedOutput(); err != nil {
		return fmt.Errorf("安装自身应用失败: %w (输出: %s)", err, strings.TrimSpace(string(out)))
	}

	_ = exec.Command(i.cliPath, "start", appName).Run()
	slog.Info("产品自身桌面图标已更新并就绪", "appName", appName, "uiType", settings.PortalUIType, "allUsers", settings.PortalAllUsers)
	return nil
}

func sanitizeAppName(id string) string {
	id = strings.ToLower(strings.TrimSpace(id))
	var sb strings.Builder
	for _, c := range id {
		if (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') || c == '-' || c == '_' {
			sb.WriteRune(c)
		} else {
			sb.WriteRune('-')
		}
	}
	res := strings.Trim(sb.String(), "-_")
	if res == "" {
		res = "app"
	}
	return res
}

// SanitizeFileName cleans up a filename to be safe on the filesystem.
func SanitizeFileName(name string) string {
	name = filepath.Base(name)
	var sb strings.Builder
	for _, c := range name {
		if (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '.' || c == '-' || c == '_' {
			sb.WriteRune(c)
		} else {
			sb.WriteRune('_')
		}
	}
	res := strings.Trim(sb.String(), "._-")
	if res == "" {
		res = "icon.png"
	}
	return res
}
